name: GitHub-Profile-Summary-Cards

on:
  create:
  push:
  schedule: # execute once a week - 24 hours was overkill for this honestly
    - cron: "0 0 * * FRI"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate

    steps:
      - uses: actions/checkout@v2
      - uses: vn7n24fzkq/github-profile-summary-cards@release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          USERNAME: ${{ github.repository_owner }}
